// Auth Types
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const STORE_USER = 'STORE_USER';

// Category Types
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';

// Subcategory Types
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const GET_ALL_SUBCATEGORIES = 'GET_ALL_SUBCATEGORIES';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';

// Designers Types
export const GET_ALL_DESIGNERS = 'GET_ALL_DESIGNERS';
export const GET_DESIGNER = 'GET_DESIGNER';
export const GET_DESIGNERS_COUNT = 'GET_DESIGNERS_COUNT';
export const GET_DESIGNERS = 'GET_DESIGNERS';
export const SORT_DESIGNERS_BY_DATE = 'SORT_DESIGNERS_BY_DATE';
export const SORT_DESIGNERS_BY_LIKES = 'SORT_DESIGNERS_BY_LIKES';
export const GET_DESIGNERS_BY_TYPE = 'GET_DESIGNERS_BY_TYPE';

// Advertisments Types
export const ADD_NEW_ADVERTISMENT = 'ADD_NEW_ADVERTISEMENT';
export const GET_ALL_ADVERTISEMENTS = 'GET_ALL_ADVERTISEMENTS';
export const DELETE_ADVERTISEMENT = 'DELETE_ADVERTISEMENT';
